# Generated by Django 4.1.5 on 2023-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="id",),
        migrations.AddField(
            model_name="product",
            name="product_description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
