# Generated by Django 4.1.5 on 2023-01-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_id_product_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="product_added_date",),
        migrations.RemoveField(model_name="product", name="product_name",),
        migrations.AddField(
            model_name="product",
            name="about",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
